<h2 style="text-align: center;"><b>Python. Занятие 1: Основы</b></h2>

## Основы Python

### Структуры данных и встроенные функции

**Все типы данных** в Python относятся к одной из **2-х категорий**: **изменяемые (mutable)** и **неизменяемые (unmutable)**.   

*Неизменяемые объекты*:  
* числовые данные (int, float), 
* bool,
* None,
* символьные строки (class 'str'), 
* кортежи (tuple).  

*Изменяемые объекты*:  
* списки (list), 
* множества (set), 
* словари (dict).  

Вновь определяемые пользователем типы (классы) могут быть определены как неизменяемые или изменяемые. Изменяемость объектов определённого типа является принципиально важной характеристикой, определяющей, может ли объект такого типа **выступать в качестве ключа для словарей (dict)** или нет.

### tuple

In [ ]:
t = ('a', 5, 12.345)
t


('a', 5, 12.345)

In [ ]:
t.append(5)

AttributeError: ignored

In [ ]:
len(t)

3

#### Поменять переменные местами

In [ ]:
a = -5
b = 100

a, b = b, a

print('a:', a, '\nb:', b)

### list

In [ ]:
a = list()
b = []

print(a == b)

In [ ]:
my_list = ['string', 100, 5.678, None]
my_list

In [ ]:
array = [37,34,26,85,67,96,53,42,45,65,74,78,]
array = list(array)
print(array, '|', type(array))

[37, 34, 26, 85, 67, 96, 53, 42, 45, 65, 74, 78] | <class 'list'>


In [ ]:
array[1]

In [ ]:
array[-1]

In [ ]:
for i in range(2,10, 2):
    print(i)

2
4
6
8


* Перевернуть список:

In [ ]:
array = array[::-1]
array

[78, 74, 65, 45, 42, 53, 96, 67, 85, 26, 34, 37]

* Срезы (`slice`'s) - это объекты языка Python, позволяющие получить какую-то часть итерируемого объекта.  
Пример:

In [ ]:
foo = list(range(10))
foo

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
foo[:5]

[0, 1, 2, 3, 4]

In [ ]:
foo[5:]

In [ ]:
foo[2:5]

[2, 3, 4]

* Списки можно "склеивать":

In [ ]:
a = [1, 2, 3]
b = [4, 5, 6]

print(a + b)

[1, 2, 3, 4, 5, 6]


### Задание 1

1. Даны два списка одинаковых размеров из одинаковых элементов:  
`items = [1 5 6 9 8 7 2 3 4]`  
`shuffled_items = [2 3 4 1 6 5 7 9 8]`  

2. Расставьте элементы (с помощью функции `sort()`) в списоке `items` так, чтобы получился список `shuffled_items`  

In [ ]:
items = [1, 5, 6, 9, 8, 7, 2, 3, 4]
shuffled_items = [2, 3, 4, 1, 6, 5, 7, 9, 8]
items.sort(key=lambda x: shuffled_items.index(x))
print(items)
print(shuffled_items)

[2, 3, 4, 1, 6, 5, 7, 9, 8]
[2, 3, 4, 1, 6, 5, 7, 9, 8]


---

### enumerate, zip

In [ ]:
first = 'a b c d e f g'.split(' ')
second = '1 2 3 4 '.split(' ')
print(first, second)
zip(first, second)

['a', 'b', 'c', 'd', 'e', 'f', 'g'] ['1', '2', '3', '4', '']


In [ ]:
first, second

(['a', 'b', 'c', 'd', 'e', 'f', 'g'], ['1', '2', '3', '4', ''])

In [ ]:
list(zip(first, second * 3, first, second * 2))

[('a', '1', 'a', '1'),
 ('b', '2', 'b', '2'),
 ('c', '3', 'c', '3'),
 ('d', '4', 'd', '4'),
 ('e', '', 'e', ''),
 ('f', '1', 'f', '1'),
 ('g', '2', 'g', '2')]

---

### Задание 2

1. Создайте список `a`, состоящий из каких-то элементов.
2. Создайте список `b` такого же размера, как `a`, состоящий из каких-то элементов.
3. Выведите нумерованный список пар из элементов списков `a` и `b`.

In [ ]:
a, b = ['a', 'b', 'c'], [1, 6, 9]
for i, pair in enumerate(zip(a, b)):
    print(f"IDX: {i}, PAIR: {pair}")

IDX: 0, PAIR: ('a', 1)
IDX: 1, PAIR: ('b', 6)
IDX: 2, PAIR: ('c', 9)


---

### Задание 3

*Выведите* список из 100 чисел *через запятую*. **Чистыми циклами пользоваться нельзя.** (list comprehensions можно)

In [ ]:
", ".join([str(i) for i in range(100)])

'0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99'

---

In [ ]:
l = ['agfkd.,f', 'Qksdf;sb&..', 'asdoo*', 'bgf...d', 're54()kj[]].']
for num, s in zip([x.count('.') for x in l], l):
    if num > 2:
        print(s)

bgf...d


In [ ]:
[s for num, s in zip([x.count('.') for x in l], l) if num > 2]

---

### modules

**Модули** - это "библиотеки" Python. То есть это самостоятельные, объединённые технически и логически, именованные части Python кода

* О модулях необходимо знать только одно - как их импортировать:

In [ ]:
import collections

* Импортировать только какой-то компонент из модуля:

In [ ]:
from collections import Counter

* Импортировать с другим именем (чаще всего используется для локаничности кода):

In [ ]:
import collections as cl

In [ ]:
count = cl.Counter()

Жизненный пример:

In [ ]:
import numpy as np

### files

In [ ]:
!echo 'test file for python-intro notebook' > test.txt

In [ ]:
path = './test.txt'

In [ ]:

file = open(path, mode='r')
print([line for line in file][0])
file.close()

test file for python-intro notebook



| Режим | Обозначение |
|-------|-------------|
| **'r'**  | Открытие на **чтение** (является значением по умолчанию) |
| **'rb'** | Открытие на **чтение**, в предположении, что будут считываться **байты** |
| **'w'** | Открытие на **запись**, содержимое файла удаляется. Если файла не существует, создается новый |
| **'wb**' | Открытие на **запись байтов**, содержимое файла удаляется. Если файла не существует, создается новый |
| **'a'** | Открытие на **дозапись**, информация добавляется **в конец файла** |
| **'r+'** | Открыть файл на **чтение И запись**. Если файла нет, **новый НЕ создаётся** |
| **'a+'** | Открыть файл на **чтение И запись в конец файла**. Если файла нет, **новый создаётся** |
| **'t'** | Открытие файла **как текстового** (по умолчанию) |

In [ ]:
with open(path, mode='r') as test_file:
    for line in test_file:
        print(line)



test file for python-intro notebook



### exceptions

In [ ]:
dir(__builtin__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [ ]:
raise KeyboardInterrupt()

KeyboardInterrupt: ignored

In [ ]:
my_dict = {1: 100, 2: 200}
print(my_dict['NEW'])

KeyError: ignored

In [ ]:
try:
    my_dict = {1: 100, 2: 200}
    print(my_dict['NEW'])
except KeyError:
    print('Caught KeyError!')

Caught KeyError!


### Полезные библиотеки Python

### glob

In [ ]:
import glob

In [ ]:
!dir

sample_data  test.txt


In [ ]:
glob.glob('./[0-9].*')

[]

In [ ]:
glob.glob('*.png')

[]

In [ ]:
glob.glob('?.jpg')

[]

In [ ]:
glob.glob('./**/', recursive=True)

['./', './sample_data/']

In [ ]:
glob.glob('**/*.txt', recursive=True)

['test.txt']

### tqdm

* Устанавливаем виджеты:

`pip install ipywidgets`  

(или `conda install -c conda-forge ipywidgets`)

* Разрешаем их использование в Jupyter Notebook:  

`jupyter nbextension enable --py --sys-prefix widgetsnbextension`  

* Перезагружаем ядро (Restart Kernel)  


* Устанавливаем tqdm:  

`pip install tqdm`  

(или `conda install -c conda-forge tqdm`)  

Больше про tqdm: https://pypi.python.org/pypi/tqdm

In [ ]:
from tqdm import tqdm
from tqdm import tnrange, tqdm_notebook
from time import sleep

In [ ]:
cnt = 0
for i in tqdm(range(1000)):
    sleep(0.01)
    cnt += 1

100%|██████████| 1000/1000 [00:10<00:00, 97.19it/s]


In [ ]:
for i in tnrange(10, desc='1st loop'):
    print(i)
    for j in tqdm_notebook(range(100), desc='2nd loop', leave=False):
        print(j)
        sleep(0.01)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: TqdmDeprecationWarning: Please use `tqdm.notebook.trange` instead of `tqdm.tnrange`
  """Entry point for launching an IPython kernel.


1st loop:   0%|          | 0/10 [00:00<?, ?it/s]

0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  This is separate from the ipykernel package so we can avoid doing imports until


2nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
1


2nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
2


2nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
3


2nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
4


2nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
5


2nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
6


2nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
7


2nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
8


2nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
9


2nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


### collections

* `defaultdict()` - класс словаря, у которого есть значение по умолчанию - порой очень пригождается:

In [ ]:
from collections import defaultdict

In [ ]:
d = defaultdict(int)

print(d.get('key', 0))

d['key'] = 5
print(d['key'])  # 5

0
5


In [ ]:
d = defaultdict(lambda: 'empty')
print(d['key'])

d['key'] = 'full'
print(d['key'])

empty
full


In [ ]:
temp = defaultdict(lambda: 'empty')
temp['trata']
print(temp.keys(), temp['trata'])

In [ ]:
d = dict()
print(d)
if 'list1' in d.keys():
    d['list1'].append(100)
    d['list1'].append(200)
else:
    d['list1'] = []
print(d)
print(d['list1'])

* `Counter()` - класс словаря, предназначенного для счётчиков. По сути, `== defaultdict(int)`:

In [ ]:
from collections import Counter

In [ ]:
counter = Counter()

for word in dir(__builtin__):
    for letter in word:
        counter[letter] += 1  # или .update(value)
    
print(counter)

---

# Библиотека Numpy.
- ***``Numpy`` - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.***


- ***Пакет ``Numpy`` предоставляет $n$-мерные однородные массивы (все элементы одного типа) в них нельзя вставить или удалить элемент в произвольном месте. В ``Numpy`` реализовано много операций над массивами в целом.***

In [ ]:
# !conda install numpy
# !pip3 install numpy

In [2]:
import numpy as np

## 1. Одномерные массивы

***Если вы не знаете нужной функции, но понимаете, чего хотите, тогда можно воспользоваться поиском в документации.***

In [ ]:
np.lookfor('mean value of array') 

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Return input with invalid data masked and replaced by a fill value.
numpy.matrix.partition
    R

***Далее можно почитать документацию про контретную функцию.***

In [ ]:
?np.ma.mean

In [ ]:
np.con*?

***Посмотрим на количественные характеристики ``ndarray``.***

In [ ]:
arr = np.array([[[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]], 
                [[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]]])
print(arr)
#print(arr[0:1,1:2,0:1])


[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [ ]:
print("len:", len(arr), "-- количество элементов по первой оси.",
      "\nsize:", arr.size, "-- всего элементов в матрице.",
      "\nndim:", arr.ndim, "-- размерность матрицы.",
      "\nshape:", arr.shape, "-- количество элементов по каждой оси.")

len: 2 -- количество элементов по первой оси. 
size: 24 -- всего элементов в матрице. 
ndim: 3 -- размерность матрицы. 
shape: (2, 3, 4) -- количество элементов по каждой оси.


***Индексы.***

In [ ]:
a = np.array([1, 2, 3, 4])
a[0], a[-1]

(1, 4)

***Последний элемент.***

In [ ]:
a[-1]

***Можем изменять объекты массива.***

In [ ]:
a[2] = -1
a

array([ 1,  2, -1,  4])

### **Задача 1:** 
Создать numpy-массив, состоящий из первых четырех простых чисел, выведите его тип и размер:

In [4]:
# решение

arr = np.array([2, 3, 5, 7])
print(type(arr), arr.size)

<class 'numpy.ndarray'> 4


## Создание массивов.

In [ ]:
a = np.zeros(7) # массив из нулей
b = np.ones(7, dtype=np.int16) # массив из единиц
print(a)
print(b*4)

[0. 0. 0. 0. 0. 0. 0.]
[4 4 4 4 4 4 4]


***Часто нужно создать нулевой массив такой же как другой.***

In [ ]:
c = np.zeros(7)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
c = np.zeros_like(b)
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

***Функция `np.arange` подобна `range`. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда (конец-начало)/шаг -- целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.***

In [ ]:
a = np.arange(1, 16, 4)
b = np.arange(5., 21, 2)
c = np.arange(1, 10)
d = np.arange(5)
print(a)
print(b)
print(c)
print(d)

[ 1  5  9 13]
[ 5.  7.  9. 11. 13. 15. 17. 19.]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


***Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`. Начало и конец диапазона включаются; последний аргумент -- число точек.***

In [ ]:
a = np.linspace(1, 15, 2)
b = np.linspace(5, 12, 10)
print(a)
print(b)

[ 1. 15.]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


### **Задача 2:** 
создать и вывести последовательность чисел от 10 до 32 с постоянным шагом, длина последовательности -- 12. Чему равен шаг?

In [5]:
# решение

arr = np.linspace(10, 32, 12)
print(*arr)
print(arr[1] - arr[0])


10.0 12.0 14.0 16.0 18.0 20.0 22.0 24.0 26.0 28.0 30.0 32.0
2.0


***Последовательность чисел с постоянным шагом по логарифмической шкале от $10^0$ до $10^3$.***

In [6]:
#решенение

arr = np.logspace(1, 10**3)
print(*arr)


10.0 2.4420530945486545e+21 5.963623316594661e+41 1.4563484775012623e+62 3.55648030622315e+82 8.68511373751352e+102 2.1209508879202446e+123 5.179474679231308e+143 1.2648552168553114e+164 3.0888435964774976e+184 7.543120063354608e+204 1.8420699693267013e+225 4.498432668969674e+245 1.0985411419875348e+266 2.682695795279826e+286 6.551285568595281e+306 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf


c:\Miniconda3\lib\site-packages\numpy\core\function_base.py:277: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


## 2. Операции над одномерными массивами.

***Все арифметические операции производятся поэлементно.***

In [ ]:
print(a)
print(b)

[ 1. 15.]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


In [ ]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


***Один из операндов может быть скаляром, а не массивом.***

In [ ]:
print(5/a)
print(10 + b)

[1.66666667 0.83333333 0.55555556 0.41666667 0.33333333 0.27777778
 0.23809524 0.20833333 0.18518519 0.16666667 0.15151515]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [ ]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


In [ ]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [ ]:
np.log(a)

array([1.09861229, 1.79175947, 2.19722458, 2.48490665, 2.7080502 ,
       2.89037176, 3.04452244, 3.17805383, 3.29583687, 3.40119738,
       3.49650756])

***Логические операции также производятся поэлементно.***

In [ ]:
print(a > b)
print(a == b)
print(a >= 10)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


In [ ]:
print(np.e, np.pi)

2.718281828459045 3.141592653589793


***Посмотрим на сортировку numpy-массивов.***

In [ ]:
a = np.array([1, 5, 6, 10, -2, 0, 18])

In [ ]:
print(np.sort(a))
print(a)

[-2  0  1  5  6 10 18]
[ 1  5  6 10 -2  0 18]


***Теперь попробуем как метод.***

In [ ]:
a.sort()
print(a)

[-2  0  1  5  6 10 18]


In [ ]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

## Индексирование массивов и срезы

***Массив в обратном порядоке.***

In [ ]:
print(a)
a[::-1]

[-2  0  1  5  6 10 18]


array([18, 10,  6,  5,  1,  0, -2])

***Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.***

In [ ]:
print(a)

[-2  0  1  5  6 10 18]


In [ ]:
a[2:5]

array([1, 5, 6])

In [ ]:
b = a[0:6] # копия не создается
b[1] = -1000
print(a)

[   -2 -1000     1     5     6    10    18]


***Диапозоны с шагами.***

In [ ]:
b = a[0:4:2]
print(b)

# подмассиву можно присваивать скаляр
a[1:6:3] = 0
print(a)

[-2  1]
[-2  0  1  5  0 10 18]


### **Задание 3:**  
- Создать массив чисел от $-4\pi$  до $4\pi $, количество точек 100
- Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива  
- С помощью ``np.all`` проверить, что все элементы равны единице.

In [7]:
# решение

arr = np.linspace(-4 * np.pi, 4 * np.pi, 100)
sums = [0 for _ in range(len(arr))]
for i in range(len(arr)):
    sums[i] = np.sin(arr[i])**2 + np.cos(arr[i])**2
print(np.all(sums) == 1)


True


## 3. Двумерные массивы

In [ ]:
a = np.array([[1, 2], [3, 4], [3,6]])
print(a)

[[1 2]
 [3 4]
 [3 6]]


In [ ]:
a.ndim, a.shape, len(a), a.size

(2, (3, 2), 3, 6)

***Обращение по индексу.***

In [ ]:
a[1][1], a[1,1]

(4, 4)

In [ ]:
a = np.ones((3, 3)) # подать tuple
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b = np.zeros((3, 4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### ***Задание 4:***
Создать квадратную матрицу размера 8, на главной диаг. арифметическая прогрессия с шагом 3 (начиная с 3), а на побочной -1, остальные элементы 0.

In [15]:
# решение

arr = np.diag(np.array([i for i in range(3, 3 * (8 + 2), 3)]))
j = -1
for i in range(arr.shape[0]):
    arr[i, j] = 4 + j
    j -= 1

print(arr)


[[ 3  0  0  0  0  0  0  0  3]
 [ 0  6  0  0  0  0  0  2  0]
 [ 0  0  9  0  0  0  1  0  0]
 [ 0  0  0 12  0  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0  0]
 [ 0  0  0 -2  0 18  0  0  0]
 [ 0  0 -3  0  0  0 21  0  0]
 [ 0 -4  0  0  0  0  0 24  0]
 [-5  0  0  0  0  0  0  0 27]]


***Умножение матриц.***

In [ ]:
a = 5*np.ones((5, 5))
b = np.eye(5) + 1
print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [ ]:
print(a*b, '\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b)) 
a =np.array([2,5,8])
b= np.array([5,3,7])
print(a.dot(b))

[10 15 56] 

81 

81
81


***Маски.***

In [ ]:
a = np.arange(20)
print(a)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


***След (trace) - сумма диагональных элементов.***

In [ ]:
b = np.diag(a[a >= 10])
print(b)
print(np.trace(b))

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145


## 4. Тензоры (многомерные массивы)

In [ ]:
X = np.arange(64).reshape(8, 2, 4)
print(np.arange(64))
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [ ]:
X.shape, len(X), X.size, X.ndim

((8, 2, 4), 8, 64, 3)

***Посмотрим на суммы по разным осям.***

In [ ]:
print(np.sum(X, axis=0), '\n')
print(np.sum(X, axis=1), '\n')
print(np.sum(X, axis=2), '\n')

# суммируем сразу по двум осям, то есть для фиксированной i 
# суммируем только элементы с индексами (i, *, *)
print(np.sum(X, axis=(1, 2)))

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]] 

[ 28  92 156 220 284 348 412 476]


## 5. Линейная алгебра

In [ ]:
a = np.array([[2, 1], [2, 3]])
print(a)

[[2 1]
 [2 3]]


***Определитель.***

In [ ]:
np.linalg.det(a)

4.0

***Нахождениия обратной.***

In [ ]:
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


# Pandas

Библиотека `pandas` активно используется в современном data science для работы с данными, которые могут быть представлены в виде таблиц (а это очень, очень большая часть данных)

`pandas` есть в пакете Anaconda, но если вдруг у Вас её по каким-то причинам нет, то можно установить, раскомментировав одну из следующих команд:

In [ ]:
# !pip3 install pandas
# !conda install pandas

In [18]:
import numpy as np
import pandas as pd # Стандартное сокращение для pandas. Всегда используйте его!

## pd.Series

Тип данных pd.Series представляет собой одномерный набор данных. Отсутствующий данные записываются как `np.nan` (в этот день термометр сломался или метеоролог был пьян); они не участвуют в вычислении средних, среднеквадратичных отклонений и т.д.

### Создание
Создадим Series из списка температур

In [ ]:
some_list = [1, 3, 5, np.nan, 6, 8]
ser_1 = pd.Series(some_list)
ser_1

In [ ]:
# Так же можно в явном виде указать индексы, чтобы потом было более удобно обращаться к элементам
ind = ['1st day', '2nd day', '3rd day', '4th day', '5rd day', '6th day']

ser_2 = pd.Series(some_list, index=ind)
ser_2

In [ ]:
ser_2.index

In [ ]:
ser_2['4th day']

In [ ]:
# А еще можно дать pd.Series имя, чтобы было совсем красиво
ser_3 = pd.Series(some_list, index=ind, name='Temperature')
ser_3

### Индексирование
С индексами можно работать так же, как и в случае с обычным list.

In [ ]:
print(ser_3[0])

print('-----------')

print(ser_3[1:3])

print('-----------')

print(ser_3[::-1])

### Индексирование pd.Series по условиям

In [ ]:
date_range = pd.date_range('20190101', periods=10)
ser_4 = pd.Series(np.random.rand(10), index=date_range)
ser_4

In [ ]:
ser_4 > 0.5

В качестве индекса можно указать выражение, и нам будут возвращены только те элементы, для которых значение является `True`

In [ ]:
ser_4[ser_4 > 0.5]

In [ ]:
ser_4[(ser_4 > 0.6) | (ser_4 < 0.2)]

In [ ]:
ser_4[(ser_4 > 0.6) & (ser_4 < 0.2)]

### Сортировки
Тип `pd.Series` можно отсортировать как по значениям, так и по индексу.

In [ ]:
ser_4.sort_index()

In [ ]:
ser_4 = ser_4.sort_values()

In [ ]:
ser_4

### Операции с series
Тип `pd.Series` можно модифицировать проще, чем стандартный ``list`` из Python.

In [ ]:
ser_4 + 100

In [ ]:
np.exp(ser_4)

In [ ]:
term_1 = pd.Series(np.random.randint(0, 10, 5))
term_2 = pd.Series(np.random.randint(0, 10, 6))

term_1 + term_2

In [ ]:
term_1.shape

# pd.DataFrame

Тип данных pd.DataFrame представляет собой двумерную таблицу с данными. Имеет индекс и набор столбцов (возможно, имеющих разные типы). Таблицу можно построить, например, из словаря, значениями в котором являются одномерные наборы данных.
### Создание и основные объекты

In [ ]:
# Dataframe можно составить из словаря. Ключ будет соответсовать колонке
some_dict = {'one': pd.Series([1,2,3], index=['a','b','c']),
             'two': pd.Series([1,2,3,4], index=['a','b','c','d']),
             'three': pd.Series([5,6,7,8], index=['a','b','c','d'])}
df = pd.DataFrame(some_dict)
df

In [ ]:
#Альтернативно, из списка списков с аргументом columns

some_array = [[1,1,5], [2,2,6], [3,3,7], [np.nan, 4,8]]
df = pd.DataFrame(some_array, index=['a', 'b', 'c', 'd'], columns=['one', 'two', 'three'])
df

In [ ]:
df.values

In [ ]:
df.columns

Index(['one', 'two', 'three'], dtype='object')

In [ ]:
df.columns = ['first_column', 'second_column', 'third_column']
df.index = [1,2,3,4]
df

### Индексирование 
Есть очень много способов индексировать DataFrame в Pandas. Не все из них хорошие! Вот несколько удобных, но не универсальных.

#### По колонкам
Индексирование по колонке возращает pd.Series. Можно выбирать не одну колонку, а сразу несколько. Тогда снова вернётся pd.DataFrame.

In [ ]:
first_column = df['first_column']
first_column

In [ ]:
df.first_column

In [ ]:
subset_dataframe = df[['first_column', 'second_column']]
subset_dataframe

In [ ]:
one_column_dataframe = df[['first_column']]
one_column_dataframe

#### По строкам
Можно писать любые слайсы, как в Python-списке. Они будут применяться к строкам. Нельзя обращаться по элементу!

In [ ]:
df[1] # не сработает

In [ ]:
df[:1]

In [ ]:
df[1:4]

#### Универсальное индексирование: .loc и .iloc

.loc и .iloc --- это два взаимозаменяемых атрибута, которые позволяют индексировать по обеим осям сразу. Путаницы не возникает из-за фиксированного порядка перечисления осей.

In [ ]:
# По индексам: 
df.iloc[1:3, :2]

In [ ]:
df.loc[1:3, ['first_column', 'second_column']]

Лучше использовать по умолчанию либо только loc, либо только .iloc! А лучше вообще всегда только .iloc, чтобы не запутаться.

### Модификации датасета, создание новых колонок
Можно просто брать и создавать новую колонку. Синтаксис тут вполне естественный.

In [ ]:
new_column = [5,2,1,4]
df['new_column'] = new_column
df

Аналогично, можно применять к отдельным колонкам арифметические операции (ведь колонки --- это Series!)

In [ ]:
df['first_column'] = df['first_column'] * 10
df

## Реальный датасет
Мы будем работать с датасетом ``Титаник``. Файлы необходимо скачать локально или загрузить с помощью функции ниже.
![alt text](https://drive.google.com/uc?id=1Tb52nFFsjI8sqv0AlMpx25aNJ62xzp5w)

Информация о файлах: 
 - *titanic_data.csv* содержит различную информацию о пассажирах Титаника (билет, класс, возраст и т.п.)
 - *titanic_surv.csv* содержит для каждого пассажира из первого файла информацию о том, выжил ли этот пассажир (метка 1) или нет (метка 0)


### Чтение из файла
Обычно данные хранятся в виде таблиц в файлах формата .csv или .xlsx. На этом семинаре мы будем загружать данные из .csv файлов.


 
Загрузим первый файл

In [19]:
# df_1 = pd.read_csv('titanic_data.csv')
pass_link = 'https://www.dropbox.com/s/lyzcuxu1pdrw5qb/titanic_data.csv?dl=1'
titanic_passengers = pd.read_csv(pass_link, index_col='PassengerId') # index_col=?

In [ ]:
print('Всего пассажиров: ', len(titanic_passengers))
titanic_passengers.head(10)

### Разная информация о датасете

Можно узнать размер таблицы, информацию о значениях таблицы, различные статистики по значениям.

In [ ]:
titanic_passengers.shape

In [ ]:
titanic_passengers.info()

In [ ]:
titanic_passengers.describe()

## Задание 1 
Опишите данный датасет: какое расределение женщин/мужчин в нем? Сколько пассажиров ехало в каждом классе? Какой средний/минимальный/максимальный возраст пассажиров?

In [ ]:
(titanic_passengers['Age'].min(), titanic_passengers['Age'].mean(), titanic_passengers['Age'].max())

In [ ]:
titanic_passengers['Sex'].value_counts()

In [ ]:
titanic_passengers['Pclass'].value_counts()

## Задание 2
Сгруппируйте записи по классам пассажиров, в каждой группе посчитайте средний возраст. Используйте метод ``pandas.DataFrame.groupby``.

In [20]:
# решение
groups = titanic_passengers.groupby(by = 'Pclass').mean()['Age']
print(*groups)


38.233440860215055 29.87763005780347 25.14061971830986


C:\Users\papey08\AppData\Local\Temp/ipykernel_9116/2488226389.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groups = titanic_passengers.groupby(by = 'Pclass').mean()['Age']


## Слияние таблиц
Таблицы можно сливать несколькими способами. Мы рассмотрим слияние по индексу: метод называется ``pd.join``.

In [ ]:
# df_2 = pd.read_csv('titanic_surv.csv')
surv_link = 'https://www.dropbox.com/s/v35x9i6a1tc7emm/titanic_surv.csv?dl=1'
df_2 = pd.read_csv(surv_link)

In [ ]:
df_2.head()

### Задание 3.
Слейте два датасета по колонке индекса.

In [21]:
# решение

link_1 = 'https://www.dropbox.com/s/lyzcuxu1pdrw5qb/titanic_data.csv?dl=1'
df_1 = pd.read_csv(link_1)

link_2 = 'https://www.dropbox.com/s/v35x9i6a1tc7emm/titanic_surv.csv?dl=1'
df_2 = pd.read_csv(link_2)

df_joined = df_1.join(df_2) 

df_joined.head()


PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

### Задание 4. 
Сколько всего выживших пассажиров? Выживших пассажиров по каждому из полов? Постройте матрицу корреляций факта выживания, пола и возраста.

In [26]:
# решение

df_2.head()
a_sex = df_joined.groupby(by = 'Sex')['Survived'].sum()
print('Всего выживших', sum(a_sex))
print(a_sex)
k = df_joined[['Sex', 'Age', 'Survived']]
k.loc[(k['Sex'] == 'female'), 'Sex'] = 1
k.loc[(k['Sex'] == 'male'), 'Sex'] = 0
k = k.fillna(0)
print('Матрица корреляций')
print(k.corr)


Всего выживших 342
Sex
female    233
male      109
Name: Survived, dtype: int64
Матрица корреляций
<bound method DataFrame.corr of      Sex   Age  Survived
0      0  22.0         0
1      1  38.0         1
2      1  26.0         1
3      1  35.0         1
4      0  35.0         0
..   ...   ...       ...
886    0  27.0         0
887    1  19.0         1
888    1   0.0         0
889    0  26.0         1
890    0  32.0         0

[891 rows x 3 columns]>


In [ ]:
import seaborn as sns

In [ ]:
sns.heatmap(
    # сюда нужно подставить матрицу корреляции
    annot=True, cmap='coolwarm',
    vmin=-1, vmax=1,
    annot_kws={"size": 16})